#!/bin/sh
VENDOR=samsung
DEVICE=espressowifi
OUTDIR=vendor/$VENDOR/$DEVICE
MAKEFILE=../../../$OUTDIR/device-partial.mk
ANDROIDMK=../../../$OUTDIR/proprietary/Android.mk
BOARDCONFIG=../../../$OUTDIR/BoardConfigVendor.mk
DEVVENDOR=../../../$OUTDIR/device-vendor.mk

(cat << EOF) > $MAKEFILE
# Copyright (C) 2012 The Android Open Kang Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh
#

PRODUCT_PACKAGES := \\
EOF

LINEEND=" \\"
COUNT=`wc -l proprietary-files.txt | awk {'print $1'}`
for FILE in `cat proprietary-files.txt`; do
    COUNT=`expr $COUNT - 1`
    if [ $COUNT = "0" ]; then
        LINEEND=""
    fi
    FILE2=`echo "${FILE##*/}"`
    FILE3=`echo "${FILE2%.*}"`
    echo "    $FILE3$LINEEND" >> $MAKEFILE
done

(cat << EOF) > $DEVVENDOR
# Copyright (C) 2012 The Android Open Kang Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh
#

LOCAL_STEM := $DEVICE/device-partial.mk
EOF
echo '$(call inherit-product-if-exists, vendor/'$VENDOR'/$(LOCAL_STEM))' >> $DEVVENDOR


(cat << EOF) > $BOARDCONFIG
# Copyright (C) 2012 The Android Open Kang Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh
#
LOCAL_STEM := $DEVICE/BoardConfigPartial.mk

EOF
echo '-include vendor/'$VENDOR'/$(LOCAL_STEM)' >> $BOARDCONFIG


(cat << EOF) > ../../../$OUTDIR/BoardConfigPartial.mk
# Copyright (C) 2012 The Android Open Kang Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh
#
# This file is supposed to be blank, its use is unknown by the creator of
# the script that generated it. Word.
EOF

(cat << EOF) > ../../../$OUTDIR/proprietary/Android.mk
# Copyright (C) 2012 The Android Open Kang Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh
#

EOF
echo 'LOCAL_PATH := $(call my-dir)' >> $ANDROIDMK
echo "" >> $ANDROIDMK
echo 'ifeq ($(TARGET_DEVICE),'$DEVICE')' >> $ANDROIDMK
echo "" >> $ANDROIDMK

COUNT=`wc -l proprietary-files.txt | awk {'print $1'}`
for FILE in `cat proprietary-files.txt`; do
    COUNT=`expr $COUNT - 1`
    if [ $COUNT = "0" ]; then
        LINEEND=""
    fi
    FILEWOPATH=`echo "${FILE##*/}"`
    FILEWOEXT=`echo "${FILEWOPATH%.*}"`
    FILEEXT=`echo "${FILEWOPATH##*.}"`
    FILEPATH=`echo "${FILE%/*}"`
    echo '    include $(CLEAR_VARS)' >> $ANDROIDMK
    echo "    LOCAL_MODULE := $FILEWOEXT" >> $ANDROIDMK
    echo "    LOCAL_MODULE_OWNER := $VENDOR" >> $ANDROIDMK
    echo "    LOCAL_SRC_FILES := $FILEWOPATH" >> $ANDROIDMK
    echo "    LOCAL_MODULE_TAGS := optional" >> $ANDROIDMK
    if [ $FILEEXT = $FILEWOPATH ]; then
	echo "    LOCAL_MODULE_CLASS := EXECUTABLES" >> $ANDROIDMK
    else
	echo "    LOCAL_MODULE_SUFFIX := .$FILEEXT" >> $ANDROIDMK
	if [ $FILEEXT = so ]; then
		echo "    LOCAL_MODULE_CLASS := PREBUILT_LIBRARIES" >> $ANDROIDMK
	elif [ $FILEEXT = apk ]; then
		echo "    LOCAL_MODULE_CLASS := APPS" >> $ANDROIDMK
	elif [ $FILEEXT = bin ]; then
		echo "    LOCAL_MODULE_CLASS := EXECUTABLES" >> $ANDROIDMK
	else
		echo "    LOCAL_MODULE_CLASS := ETC" >> $ANDROIDMK
	fi
    fi
    echo '    LOCAL_MODULE_PATH := $(TARGET_OUT)/'$FILEPATH >> $ANDROIDMK
    echo '    include $(BUILD_PREBUILT)' >> $ANDROIDMK
    echo "" >> $ANDROIDMK
done

echo "endif" >> $ANDROIDMK
